### ISSUE TITLE
Enhancement : add color personnalization

### ISSUE THREAD

**Issue by aromanet42** [jcgay/maven-color#12]
I would like to display maven goals in normal mode (no bold), and modules names in bold.

Could you add a way to personnalize colors used by this great tool ?

Thanks a lot !

**Comment by jcgay** [comment]
I will try to :)

**Comment by jcgay** [comment]
I have implemented a way to customize colors (in `dev` branch). It is documented in the [wiki](https://github.com/jcgay/maven-color/wiki/Color-customization).  
You can give it a try with latest [snapshot](http://jeanchristophegay.com/binaries/maven-color-logback-1.2-SNAPSHOT-bundle.tar.gz).

Thanks.

**Comment by aromanet42** [comment]
Wonderful :) it is exactly was I was looking for

Thanks a lot !
