### ISSUE TITLE
Does not work with Git Bash in Win7

### ISSUE THREAD

**Issue by ilaborie** [jcgay/maven-color#13]
The color work fine in a 'cmd.exe' terminal, but I'd prefere using the 'Git Bash' terminal on Windows to run maven command.
Sample output:
```
←[39m[INFO]
←[0;39m←[39m[INFO] --------------
←[0;39m←[39m[INFO] ←[36mBuilding
←[0;39m←[39m[INFO] --------------
←[0;39m←[39m[INFO]
```

**Comment by jcgay** [comment]
I will give it another try with a Windows 7 box but I can't reproduce it for now with [this one](https://github.com/jcgay/maven-color/tree/master/vm/windows).
I have installed Git 2.5.3, which one are you using ?

![git-bash](https://cloud.githubusercontent.com/assets/967336/9990896/614d1bac-6065-11e5-8cd6-75d327a05579.png)

Thanks.

**Comment by ilaborie** [comment]
I've just update the Git Bash, it's work
