### ISSUE TITLE
Plans to update dependencies (e.g., logback/slf4j)?

### ISSUE THREAD

**Issue by binkley** [jcgay/maven-color#15]
Any plans to update your SLF4J/Logback infrastructure to more recent versions?  I note Maven ships with 1.7.5, this very excellent extension uses 1.1.3.  If the "not broken, don't fix" approach holds, that's fine obviously.  This question is more from curiosity.  I did a lot of poking around how lombok can be tuned/extended:

https://github.com/binkley/binkley/tree/develop/logging/src/main/resources

Thanks!

**Comment by jcgay** [comment]
For SLF4J version, I just follow the Maven one. I don't really see reasons to use a different one.
Logback dependency is currently set to 1.1.3 as you noticed (which is the latest version as far as I know ?) and I usually update it when new versions are released.

I gave your repository a quick look, it looks like cool defaults to bootstrap a project. Do you feel `maven-color` could gain interesting features by using some of it ?

**Comment by binkley** [comment]
I'm flattered.  Not sure how it helps for maven.  One could hook into maven's -X flag and turn on debug logging as well, but not a big issue that I can tell.  Thanks!

**Comment by binkley** [comment]
The feature I want most ... I'll file as separately as #16.

**Comment by binkley** [comment]
Looking through [logback.xml](https://github.com/jcgay/maven-color/blob/master/maven-color-logback/src/main/bundle/logback.xml), there's lots of interesting hooks you could add.  For example:
* Hook into `-X` to change global log level to DEBUG
* Support per-user/per-project/per-installation `logback.properties` to override formatting
* Support per-user/per-project/per-installation `logback-included.xml` to define more appenders, e.g., a file appender to automatically capture build output while still logging to console
I've forked your repo to experiment with some of these ideas (though I'm not sure how to pull off the per-user/per-project bit).

Cheers!

**Comment by jcgay** [comment]
`mvn -X` already set level `DEBUG` on `ROOT` logger isn't it ? Or I misunderstood your point ?

I let you explore the per-user/per-project/per-installation configuration, even if I don't really know how you will be able to retrieve a per-project configuration...

Thanks for the feedback !

**Comment by jcgay** [comment]
I will be able to update Log4j 2 dependencies when https://github.com/apache/maven/commit/202f757af3aba6e1b96631de025e0ba692098009 get released.
