### ISSUE TITLE
Support per-project/per-user configuration

### ISSUE THREAD

**Issue by binkley** [jcgay/maven-color#16]
I've had no luck trawling through Maven source to find a way for configuring logging per-user or per-project.  In particular, our client has a locked-down maven installation (barring significant hoops to jump through) so we are normally unable to install maven-color, etc.

Best would be a way to change out maven logging per-user and/or per-project rather than per-installation.  Any suggestions?

**Comment by jcgay** [comment]
Ahhh the developer locked down installation, so good old memories :sob: 

I'll have a look into it but it will imply to change the maven classpath (maybe using `-Dmaven.ext.class.path`) to include all needed JARs. 
But if that works we'll have a problem to tell SLF4J which implementation to use as we will have two bindings in the classpath (`slf4j-simple` and `logback-classic`).

A good pointer: http://takari.io/book/91-maven-classloading.html

**Comment by binkley** [comment]
Note, I've filed this with Apache Maven JIRA FWIW - https://issues.apache.org/jira/browse/MNG-5932.

**Comment by jcgay** [comment]
Cool :) We'll see what they think about it !
