### ISSUE TITLE
Disable coloring ?

### ISSUE THREAD

**Issue by JimDeanSpivey** [jcgay/maven-color#18]
I am working within a Java project that makes a lot of internal use of maven during its build process. If escape characters (color codes) are in the output it fails. As a result, the only way I can successful build is to just not use maven-color, and instead use the vanilla maven. The project I am working on is https://github.com/teamed/qulice

1. Can there be a way to just disable color for the entire run? I noticed that `maven.color` is no longer a valid flag.
2. Perhaps it would be possible to auto-disable color if it detects that it is ran in batch mode?

FYI, I see a very similar ticket 3 days ago. I don't want to junk that ticket up with my issues so I made this separate ticket. Thanks.

**Comment by jcgay** [comment]
Thanks for the report !
This is very similar to #17 indeed.

1. I'm going to try to reintroduce `maven.color` property, it should work with `Logback` (at least). 
2. I'm not sure to be able to access `mvn` CLI arguments but I will look into it.

**Comment by JimDeanSpivey** [comment]
@jcgay I'm guessing the best solution is to just add the option to disable color. But if you are interested in somehow auto-disabling color output, I'd like to share a corner case for that:

The developers on Qulice project have a rather complex setup. I'm new on the project, but I believe what happens is this.

1. `mvn` is ran to build a project. This project/module happens to build a custom maven goal (qulice installs as a maven goal).
2. Their unit test invoke a mocked version of their maven goal, which prints output to the same stdout channel (this unit test output also it gets colored and breaks some of the assertions due to the escape characters).

**Comment by jcgay** [comment]
I have released a version where color can be disabled when launching `mvn`: https://github.com/jcgay/maven-color/wiki#disable-coloring

If it does not fit your needs, feel free to reopen the issue, Thanks !

I have also opened #19 to keep batch mode in mind, I'll have to take a look at your project.

**Comment by JimDeanSpivey** [comment]
@jcgay I tested with the latest version.

Setting `MAVEN_OPTS="$MAVEN_OPTS -Dmaven.color=false" ` effectively disables color for all output, even the sub-maven builds created during qulice's unit tests. Thanks for addressing this, it's certainly an edge case (a maven build that invokes other maven builds in a non-maven way!).
