### ISSUE TITLE
Restore [INFO], [WARN], [ERROR]

### ISSUE THREAD

**Issue by jcgay** [jcgay/maven-color#22]
see https://github.com/jcgay/maven-color/commit/8702b0eccd8c04f77ffc7f0269b25c19cccd9c7a

Since `maven-color` v1.3, I have removed log level from the output.  
Should they be restored ?

**Comment by Riduidel** [comment]
Yes.
Or at least, their display should be configurable. (switch them on/off)

**Comment by jcgay** [comment]
Yep I think I can do that!
