### ISSUE TITLE
Update Windows install instructions for Cygwin

### ISSUE THREAD

**Issue by binkley** [jcgay/maven-color#23]
Would you make a trivial update to your front page docs for installation under Cygwin?  Out of the box `$M2_HOME` will be a Windows-path, not a Unix one, which causes tar some grief.
```
tar zxvf /home/Brian/profile/Downloads/maven-color-logback-1.3-bundle.tar.gz -C $(cygpath $M2_HOME)
```
Use `cygpath` to turn (for example) `c:\lib\apache-maven-3.3.9` into `/cygpath/c/lib/apache-maven-3.3.9`.

**Comment by jcgay** [comment]
I have moved instructions into the [wiki](https://github.com/jcgay/maven-color/wiki) and add a note about cygwin.

Feel free to to edit them if they're not clear enough!

Thanks.
