### ISSUE TITLE
Maven 3.4 support

### ISSUE THREAD

**Issue by mattnelson** [jcgay/maven-color#27]
Maven 3.4 looks to be adding support for colorized output. Putting this out there so maven-color could flex based on the version of maven used and defer to maven when 3.4+ is used.

https://issues.apache.org/jira/browse/MNG-3507

**Comment by jcgay** [comment]
I have started a [branch](https://github.com/jcgay/maven-color/tree/gossip) with Maven 3.4.0 support.  
It mostly delegate all the coloring to Maven except that I have stripped the `[INFO]`, `[WARNING]` level. (I'll record an asciicasts of the current state). 

But if one is fine with future default color, `maven-color` will just be useless and should not be installed at all 😛
