### ISSUE TITLE
mvn-color's "build successful" notifications steal focus from the terminal

### ISSUE THREAD

**Issue by mattalexx** [jcgay/maven-color#28]
Not sure if this is a bug or a feature but can I disable it?

**Comment by jcgay** [comment]
This is not a feature :)
It should be linked to https://github.com/jcgay/maven-notifier/issues/16
I'll give it another look, do you know which notifier is used ? It will try to find one available in https://github.com/jcgay/maven-notifier/wiki#default-notifiers

You can disable desktop notifications: https://github.com/jcgay/maven-notifier/wiki#disable-notification

**Comment by jcgay** [comment]
Closed by https://github.com/jcgay/maven-notifier/issues/18
