### ISSUE TITLE
maven-surefire-plugin and the "class was missing" error

### ISSUE THREAD

**Issue by cleankod** [jcgay/maven-color#7]
After installing all the necesary stuff I get the error when trying to `clean install` my project:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project fmbank-bluecreditonline-ferryt-wsclient: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: A required class was missing while executing org.apache.maven.plugins:maven-surefire-plugin:2.17:test: com/github/jcgay/maven/color/logger/AnsiColorConsoleLogger

`$MAVEN_OPTS` is set corectly but to be sure, I ran the command with `-Djavaagent`:
mvn -Djavaagent:$HOME/.m2/maven-color-agent-0.5.jar clean install

**Comment by jcgay** [comment]
Hi,
Thanks for reporting this !

I have not tested maven 3.0.x with maven-surefire-plugin 2.17 but are you sure to have [maven-color-logger](http://dl.bintray.com/jcgay/maven/com/github/jcgay/maven/color/maven-color-logger/0.5/maven-color-logger-0.5.jar) available in your maven installation `lib/ext` folder ?

The rest of the output is colorized ?

**Comment by jcgay** [comment]
I have tested maven-color 0.5 with Maven 3.0.5 and maven-surefire-2.17 and I have not reproduced your problem :disappointed: 

Trying to pass `javaagent` value using `-D` will not work by the way as this is not a system property but a `java` option.

My testing configuration:
```
/usr/local/Cellar/maven30/3.0.5/libexec/bin/mvn -version
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 14:51:28+0100)
Maven home: /usr/local/Cellar/maven30/3.0.5/libexec
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: fr_FR, platform encoding: MacRoman
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"
```

Feel free to reopen if you still have the error.
